spring:
  application:
    name: search-service
elasticsearch:
  url: ${ELASTICSEARCH_URL}
  templates:
    - name: listen-events
      patterns: listen-events-*
      mapping-path: elastic/templates/listen-events-mappings.json
    - name: follow-events
      patterns: follow-events-*
      mapping-path: elastic/templates/follow-events-mappings.json
    - name: audio-like-events
      patterns: audio-like-events-*
      mapping-path: elastic/templates/audio-like-events-mappings.json
    - name: playlist-like-events
      patterns: playlist-like-events-*
      mapping-path: elastic/templates/playlist-like-events-mappings.json

event:
  service-name: ${spring.application.name}
  bootstrap-servers: ${KAFKA_URL}

aggregation:
  window: ${AGGREGATION_WINDOW:300s}
  cron: ${AGGREGATION_CRON:0 */5 * * * ?}

eureka:
  client:
    register-with-eureka: ${ENABLE_EUREKA:true}
    fetch-registry: ${ENABLE_EUREKA:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}
